name: aptos
description: Aptos Dart SDK.
version: 0.0.5
repository: https://github.com/0xmove/aptos

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  dio: ^5.3.0
  hex: ^0.2.0
  ed25519_edwards: 0.3.1
  pointycastle: 3.7.3
  bip39: 1.0.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  graphql: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
